image: registry.gitlab.com/cloudigrade/images/test-container

stages:
  - Test Integrade
  - Test Cloudigrade

Test Integrade:
  stage: Test Integrade
  before_script:
    - python --version
    - make install-dev
    - pip install codecov
    - apk add curl bash
    - scripts/wait-for-pipeline.sh
  script:
    - make lint
    - make test-coverage
    - codecov
  coverage: '/\d+\%\s*$/'

.before_script: &before_script
  before_script:
    - python --version
    - oc version
    - make install-dev
    - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN
    - export CLOUDIGRADE_USER="integrade-$(python -c 'from uuid import uuid4; print(str(uuid4()))')"
    - oc rsh -c cloudigrade-api $(oc get pods -o jsonpath='{.items[*].metadata.name}' -l name=cloudigrade-api) scl enable rh-postgresql96 rh-python36 -- python manage.py createsuperuser --no-input --username $CLOUDIGRADE_USER --email="$CLOUDIGRADE_USER@example.com"
    - export CLOUDIGRADE_TOKEN=$(oc rsh -c cloudigrade-api $(oc get pods -o jsonpath='{.items[*].metadata.name}' -l name=cloudigrade-api) scl enable rh-postgresql96 rh-python36 -- python manage.py drf_create_token $CLOUDIGRADE_USER | awk '{print $3}')

API:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv integrade/tests/api

UI Chrome:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv --driver Remote --capability browserName chrome --host selenium --port 4444 integrade/tests/ui
  services:
    - name: selenium/standalone-chrome
      alias: selenium

UI Firefox:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv --driver Remote --capability browserName firefox --host selenium --port 4444 integrade/tests/ui
  services:
    - name: selenium/standalone-firefox
      alias: selenium

UI Microsoft Edge:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv --driver SauceLabs --capability browserName MicrosoftEdge integrade/tests/ui
