image: registry.gitlab.com/cloudigrade/images/test-container

stages:
  - Test Integrade
  - Test Cloudigrade
  - Cleanup

Test Integrade:
  stage: Test Integrade
  before_script:
    - python --version
    - make install-dev
    - pip install codecov
  script:
    - make lint
    - make test-coverage
    - codecov
  coverage: '/\d+\%\s*$/'

.before_script: &before_script
  before_script:
    - python --version
    - oc version
    - make install-dev
    - oc login $OPENSHIFT_URL --token=$OPENSHIFT_TOKEN
    - source scripts/oc-auth.sh

API:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv integrade/tests/api

UI Chrome:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv --driver Remote --capability browserName chrome --host selenium --port 4444 integrade/tests/ui
  services:
    - name: selenium/standalone-chrome
      alias: selenium

UI Firefox:
  stage: Test Cloudigrade
  <<: *before_script
  script:
    - py.test -vvv --driver Remote --capability browserName firefox --host selenium --port 4444 integrade/tests/ui
  services:
    - name: selenium/standalone-firefox
      alias: selenium

UI Microsoft Edge:
  stage: Test Cloudigrade
  only:
    refs:
      - master
  <<: *before_script
  script:
    - py.test -vvv --driver SauceLabs --capability browserName MicrosoftEdge integrade/tests/ui


Nightly Cleanup:on-schedule:
  stage: Cleanup
  only:
    - schedules
  before_script:
    - python --version
    - oc version
    - make install-dev
  script:
    - python scripts/aws_reaper.py
