.private-shared: &private_shared
  private-shared:
    - name: 'rhel'
      image_id: 'ami-065d0be9883aa064a'
      rhel: True
      openshift: False
    - name: 'ubuntu'
      image_id: 'ami-0b817f1f3a9927361'
      rhel: False
      openshift: False
    - name: 'ubuntu-openshift'
      image_id: 'ami-0ce8a57ac2c5cb5df'
      rhel: False
      openshift: True
    - name: 'centos'
      image_id: 'ami-0c522838bc12ae928'
      rhel: False
      openshift: False
    - name: 'centos-openshift'
      image_id: 'ami-0f94fa2a144c74cf1'
      rhel: False
      openshift: True
    - name: 'RHEL-7.6_HVM_BETA-20180814-x86_64-0-Access2-GP2' # If this breaks, check that the image still exists aws.amazon.com/console
      image_id: 'ami-09ae22a8a98cc4f9d'
      rhel: True
      openshift: False
    - name: 'RHEL-7.6_HVM_GA-20181017-x86_64-0-Hourly2-GP2' # If this breaks, check that the image still exists aws.amazon.com/console
      image_id: 'ami-011b3ccf1bd6db744'
      rhel: True
      openshift: False
    - name: 'CentOS 7.4 minimal for cloudigrade'
      image_id: 'ami-0b85178a681e2db64'
      rhel: False
      openshift: False

.marketplace: &marketplace
  marketplace:
    - name: 'rhel'
      image_id: 'ami-a8d369c0' # rhel 7
      rhel: False # we don't want to bill for it
      openshift: False
    - name: 'ubuntu' # ubuntu 16.04 # TODO
      image_id: 'ami-05fb04e2687120d6b'
      rhel: False
      openshift: False
    - name: 'windows' # Microsoft Windows Server 2019 Base
      image_id: 'ami-0410d3d3bd6d555f4' # windows server image
      rhel: False
      openshift: False
      is_windows: True

.community: &community
  community:
    - name: 'ubuntu'
      image_id: 'ami-759bc50a'
    - name: 'windows' # windows server 2016 
      image_id: 'ami-0aeaed2faa756912c'
    - name: 'opensuse'
      image_id: 'ami-2b170941'
    - name: 'fedora' # fedora 28
      image_id: 'ami-0011ab01eb7fb4fbc'

profiles:
  DEV07CUSTOMER:
      # account number 439727791560 (dev07)
      images:
        owned:
          - name: 'rhel'
            image_id: 'ami-0d2e46db3ba19f204'
            rhel: True
            openshift: False
          - name: 'rhel-lvm-openshift'
            image_id: 'ami-09c521cbc20a78b49'
            rhel: True
            openshift: True
            lvm: True
          - name: 'rhel-openshift'
            image_id: 'ami-06e6c8cae9052b490'
            rhel: True
            openshift: True
          - name: 'centos'
            image_id: 'ami-0bf18d6709ff12ee8'
            rhel: False
            openshift: False
          - name: 'centos-openshift'
            image_id: 'ami-0f75a482c0696dc99'
            rhel: False
            openshift: True
          - name: 'rhel-extra-detection-methods'
            image_id: 'ami-065ce0f0a4db0cda9'
            rhel: True
            openshift: False
            rhel_enabled_repos_found: True
            rhel_product_certs_found: True
            rhel_release_files_found: True
            rhel_signed_packages_found: True
          - name: 'rhel-openshift-extra-detection-methods'
            image_id: 'ami-0a0c971e6f4a04a60'
            rhel: True
            openshift: True
            rhel_enabled_repos_found: True
            rhel_product_certs_found: True
            rhel_release_files_found: True
            rhel_signed_packages_found: True
          - name: 'RHEL-7.6_HVM_BETA-20180814-x86_64-0-Access2-GP2' # If this breaks, check that the image still exists aws.amazon.com/console
            image_id: 'ami-09ae22a8a98cc4f9d'
            rhel: True
            openshift: False
          - name: 'RHEL-7.6_HVM_GA-20181017-x86_64-0-Hourly2-GP2' # If this breaks, check that the image still exists aws.amazon.com/console
            image_id: 'ami-011b3ccf1bd6db744'
            rhel: True
            openshift: False
          - name: 'CentOS 7.4 minimal for cloudigrade'
            image_id: 'ami-0b85178a681e2db64'
            rhel: False
            openshift: False
          


        <<: *private_shared
        <<: *marketplace
        <<: *community


  DEV08CUSTOMER:
      # account number 311230538223 (dev08)
      images:
        owned:
          - name: 'rhel'
            image_id: 'ami-09f630ec35588bec4'
            rhel: True
            openshift: False
          - name: 'rhel-lvm-openshift'
            image_id: 'ami-053b2eeaaa6d13a24'
            rhel: True
            openshift: True
            lvm: True
          - name: 'rhel-openshift'
            image_id: 'ami-079f9656a5a955224'
            rhel: True
            openshift: True
          - name: 'centos'
            image_id: 'ami-0f4ef4df59416d9ab'
            rhel: False
            openshift: False
          - name: 'centos-openshift'
            image_id: 'ami-067e15718a7a1ed0a'
            rhel: False
            openshift: True

        <<: *private_shared
        <<: *marketplace
        <<: *community

  DEV10CUSTOMER:
      # account number 543234867065 (dev 10)
       images:
        owned:
          - name: 'rhel'
            image_id: 'ami-0cc60ebed1322e404'
            rhel: True
            openshift: False
          - name: 'rhel-lvm-openshift'
            image_id: 'ami-031dca721cd450709'
            rhel: True
            openshift: True
            lvm: True
          - name: 'rhel-openshift'
            image_id: 'ami-074b1944c79ab14ae'
            rhel: True
            openshift: True
          - name: 'centos'
            image_id: 'ami-0eedc6c884d81c6ed'
            rhel: False
            openshift: False
          - name: 'centos-openshift'
            image_id: 'ami-0f51fd32846a3ff4d'
            rhel: False
            openshift: True

        <<: *private_shared
        <<: *marketplace
        <<: *community
