"""Constants for the API URL paths."""

AUTH_ME = '/auth/me/'
AUTH_PASSWORD = '/auth/password/'
AUTH_TOKEN_CREATE = '/auth/token/create/'
AUTH_TOKEN_DESTROY = '/auth/token/destroy/'
AUTH_USERS_CREATE = '/auth/users/create/'
USER_LIST = '/api/v1/user/'
CLOUD_ACCOUNT = '/api/v1/account/'
REPORT_ACCOUNTS = '/api/v1/report/accounts/'
REPORT_IMAGES = '/api/v1/report/images/'
REPORT_INSTANCES = '/api/v1/report/instances/'
IMAGE = '/api/v1/image/'
INSTANCE = '/api/v1/instance/'
SYSCONFIG = '/api/v1/sysconfig/'
SYSCONFIG_V2 = '/api/v2/sysconfig'
